/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

var x = 1;
var y = 2;
var z = 0;
var sum = 0;

while (z < 4000000) {
	z = y + x;
	x = y;
	y = z;
	console.log(x);

	if (z % 2 === 0){
		sum += z;
		console.log("Evens add to: " + sum);
	};
};

